export const
  HOVER_OPACITY: number = 0.9,
  DISABLE_OPACITY: number = 0.8,
  HOVERING_DURATION: number = 200,
  LUMINOSITY_LIGHT: number = 0.7,
  LUMINOSITY_DARK: number = 0.05,
  BG_TO_LIGHTER: number = 0.3,
  TEXT_TO_LIGHTER: number = 1,
  TEXT_TO_LIGHTEN: number = 0.9,
  BG_TO_DARKER: number = 0.1,
  BG_TO_DARKEN: number = 0.25,
  TEXT_TO_DARKER: number = 0.05,
  TEXT_TO_DARKEN: number = 0.5,
  BG_TO_OPACITY: number = 0.5,
  TOUCH_OPACITY: number = 0.6;
